TOL_TWO_PHASE_STABILITY_CONVERGENCE = 1e-11
TOL_TWO_PHASE_STABILITY_CONVERGENCE_TRIVIAL_SOLUTION = 1e-11
TOL_TWO_PHASE_FLASH_BISECTION_CONVERGENCE = 1e-14
TOL_TWO_PHASE_FLASH_CONVERGENCE = 1e-14
TOL_TWO_PHASE_FLASH_TRIVIAL_SOLUTION = 1e-05
TOL_SAT_PRESSURE = 1e-14
CONSTANT_R = 8.31