TOL_TWO_PHASE_STABILITY_CONVERGENCE = 1e-6
TOL_TWO_PHASE_STABILITY_CONVERGENCE_TRIVIAL_SOLUTION = 1e-4
TOL_TWO_PHASE_FLASH_BISECTION_CONVERGENCE = 1e-13
TOL_TWO_PHASE_FLASH_CONVERGENCE = 1e-9
TOL_TWO_PHASE_FLASH_TRIVIAL_SOLUTION = 1e-07
TOL_SAT_PRESSURE = 1e-6
CONSTANT_R = 8.31