from dataclasses import dataclass

@dataclass
class ConvergenceConstants:
    two_phase_stability_convergence : ...
    two_phase_stability_convergence_trivial_solution : ...
    flash_bisection_convergence : ...
    flash_convergence : ...
    flash_convergence_trivial_solution : ...