# Глава 2. Уравнение состояния

Основной для решения задач термодинамического равновесия в нефтяном инжиниринге стало использование уравнения состояния.
Важно отметить, что уравнение состояния - инструмент поиска коэффициента сверхсжимаемости, который используется в других итеративных алгоритмах двух-/трехфазного равновесия термодинамических систем. Данные методы будут рассмотрены в главе ...

## История развития уравнений состояния

## Общий алгоритм решения УРС

Для решения УРС необходимо решить следующую систему входящих уравнений (на примере уравнения Пенга-Робинсона с поправкой Peneloux). Важно отметить, что для уравнения SRK формулы входящих величин и сама форма кубического уравнения будет отличаться, но общая система и подход к решению не изменится.

$$
\begin{cases}
a_{i} = \Omega_{a} \cdot \frac{T_{c} ^ 2 \cdot R ^ 2}{P_{c}} \cdot \alpha
\\
\alpha_{i} = [1 + m \cdot (1 - \sqrt{\frac{T}{T_{c}}})] ^ 2
\\
m = f(\omega)
\\
b_{i} = \Omega_{b} \cdot \frac{T_{c} \cdot R}{P_{c}}
\\
A_{i} = a \cdot \frac{p}{(RT)^2}
\\
B_{i} = b \cdot \frac{p}{RT}
\\
A = \sum \sum {z_{i} z_{j} \sqrt{A_{i} A_{j}} (1- k_{ij})}
\\
B = \sum {z_{i}B_{i}}
\\
c = \sum {z_{i} s_{i} b_{i}}
\\
Z^3 - (1-B)Z^2 + (A - 3B^2 -2B)Z - (AB - B^2 - B^3) = 0
\end{cases}
$$

Следует обратить внимание, что дополнительные расчетные параметры, например $a_{i}, A_{i}$ и т.д. расчитываются отдельно для каждого компонента, затем взвешиваются по правилам смешивания, а в УРС передается один параметр $A$ и $B$, в которых уже __спрятаны__ свойства всех индивидуальных компонент. Параметры $a_{i}, b_{i}, m$ напрямую зависят от критических параметров компонента и ацентрического фактора, что становится важным при работе с фракциями С6+ (будет рассмотрено в главе ...).

После решения УРС методом Кардано проводится расчет летучести для каждой компоненты, а затем выбирается корень по минимальной энергии Гиббса

        Примечание
        В процессе flash-расчета на первых итерациях можно столкнуться с нестабильностами и некорректным выбором корней. Для этого предусмотрена отдельная процедура по выбору корня на первых итерациях всего процесса расчета паро-жидкостного равновесия.



## Уравнение А.И. Брусиловского

## Проблематика использования принятых УРС