# Глава 4. Компоненты C6+
Нефтяные и газоконденсатные смеси - сложно описываемые с точки зрения компонентного состава и свойств системы. УВ системы содержат сотни различных индивидуальных компонент, в связи с чем определение доли в составе и свойств каждого компонента является критически сложным или невозможным процессом. Для примера на рисунке представлены изомеры... Идентичность структурной формулы...

Поэтому на сегодняшний день принято несколько "инженерных" подходов к описанию компонентного состава. Компонентный состав пластового флюида можно разделить на три категории[ссылка на Pedersen]:
    - Определяемые компоненты
    - Фракции
    - Остаток

Рассмотрим каждую категорию отдельно

### Определяемые компоненты
$N_{2}, CO_{2},  H_{2}S, C_{1}, C_{2}, C_{3}, iC_{4}, nC_{4}, iC_{5}, nC_{5}$ - чистые компоненты, напрямую определяемые в составе флюида. Свойства каждого из чистых компонент исследованы и известны [библиотека MNIST или как то так]. 

Возможно и выделение других чистых компонент в составе пластового флюида, например ..., но данная задача ... 

### Фракции

#### Компонентный состав. Принцип SCN
Один  из подходов заключается в объединенни элементов в псевдокомпонент на основе диапазонов температур кипения нормальных алканов.

#### Компонентно-фракционный состав

### Остаток



## Об особенностях определения свойств фракций С6+
Как рассмотрено ранее[ссылка на главу про УРС], каждый компонент моделируемой смеси должен быть охарактеризован критическим давлением, критической температурой, ацентрическим фактором, коэффициентом попарного взаимодействия и шифт-параметром. Здесь и возникает основная неопределенность: __как описать смесь множества сложных по строению и свойствам веществ, объединенных по диапазону температур кипения? Для каждого флюида эта смесь различна, а фактические свойства каждой фракции зачастую неизвестны.__ Для этого вводится понятие псевдокомпонента. Псевдокомпонент - предполагаемый компонент, представляющий фракцию средними значениями ее свойств, необходимых для решения уравнения состояния. 


#### Что-то про ИТК.... как женить PVT исследования и результаты по исследованию дегаз.нефти? + таблица Катца и 

Зачастую, свойства псевдокомпонент являются расчетными величинами и определяются по корреляционным зависимостям.

```{mermaid}
graph TD
  A[Mw, Tb] --> B[Расчет $\gamma$];
  B --> C[Расчет P_{c}];
  C --> D[Расчет T_{c}];
  D --> E[Расчет \omega];
  D --> F[Расчет v_{c}];
  F --> G[Расчет k_{ij}];
  H --> K[Расчет c{i}];
```

